### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by cetceeve** [UniRegensburg/unsere-app-fur-die-universitat-regensburg-ur-fit#76]
The top level readme as well as the ci readme need updating to reflect current state of the app

**Comment by kindOfCurly** [comment]
The GitHub Docs recommend answering the following points in a [Readme](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-readmes)
- What the project does
- Why the project is useful
- How users can get started with the project
- Where users can get help with your project
- Who maintains and contributes to the project

***

For the top level readme I would suggest the following text:


## Welcome to the URfit App

This application is being created as part of the course "Advanced Software Engineering" in the master's degree program in Media Informatics at the University of Regensburg in collaboration with the Campus MOBIL project of the Sports Center.

The application is developed while the winter semester 2020/21 and is currently still in progress.

***

## About

So that learning and movement are no longer at odds with each other, the Campus MOBIL project has set itself the goal of bringing more movement and health into students' everyday lives.

Students are not only exposed to enormous stress during exam time, but are also repeatedly confronted with challenges in their everyday student life. A lack of rest and exercise breaks between lectures often leads to students reaching a state of physical and mental overload. Also due to time pressure, the renunciation of sports as well as the resort to a fast but often unbalanced diet is pre-programmed, since there is simply no energy left to deal with one's health. Health, which is probably our most important asset, deserves exactly that.

The URfit app is a web-based application in which students can find offers for a healthier daily study routine in the form of exercise, fitness and relaxation videos and audio files. A link to Mensa offerings is also included.

[Here](https://urfit.software-engineering.education/) you can get in touch with the URfit app.

The development team can be reached by email at ur.fit.app@mailman.uni-regensburg.de.
